# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "majestic_seo_api"
  s.version = "0.9.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Majestic-12 Ltd", "Sebastian Johnsson"]
  s.date = "2012-01-29"
  s.description = "Interface for communicating with Majestic SEO's API"
  s.email = "sebastian@agiley.se"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/generators/majestic_seo/majestic_seo_generator.rb",
    "lib/generators/templates/majestic_seo.template.yml",
    "lib/majestic_seo/api/client.rb",
    "lib/majestic_seo/api/data_table.rb",
    "lib/majestic_seo/api/item_info.rb",
    "lib/majestic_seo/api/item_info_response.rb",
    "lib/majestic_seo/api/logger.rb",
    "lib/majestic_seo/api/response.rb",
    "lib/majestic_seo/api/top_back_links_response.rb",
    "lib/majestic_seo/extensions/string.rb",
    "lib/majestic_seo/railtie.rb",
    "lib/majestic_seo_api.rb",
    "majestic_seo_api.gemspec",
    "script/get_index_item_info.rb",
    "script/get_top_backlinks.rb",
    "script/open_app_get_index_item_info.rb",
    "spec/majestic_seo/client_spec.rb",
    "spec/majestic_seo/item_info_response_spec.rb",
    "spec/majestic_seo/top_back_links_response_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://developer-support.majesticseo.com/connectors/"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Interface for communicating with Majestic SEO's API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<faraday>, ["~> 0.7.6"])
      s.add_runtime_dependency(%q<faraday_middleware>, [">= 0"])
      s.add_runtime_dependency(%q<jruby-openssl>, ["~> 0.7"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<faraday>, ["~> 0.7.6"])
      s.add_dependency(%q<faraday_middleware>, [">= 0"])
      s.add_dependency(%q<jruby-openssl>, ["~> 0.7"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<faraday>, ["~> 0.7.6"])
    s.add_dependency(%q<faraday_middleware>, [">= 0"])
    s.add_dependency(%q<jruby-openssl>, ["~> 0.7"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

